### ISSUE TITLE
Missing Lable on top

### ISSUE THREAD

**Issue by ngoccuong11789** [nguyentruongky/ActiveCode#5]
Hi Ky,
I tried to test this one, but can not see the label. Can you check it?

**Comment by nguyentruongky** [comment]
plz share me more information about issue you have.

**Comment by ngoccuong11789** [comment]
I tried to run, and cannot see the textLabel above the line, here is the picture....  

<img width="376" alt="screen shot 2016-12-14 at 5 36 48 pm" src="https://cloud.githubusercontent.com/assets/16872877/21178852/fa5ebfdc-c223-11e6-8436-b8eb271a431f.png">

**Comment by ngoccuong11789** [comment]
Fix, thank you.
